const { flow } = require('./../src/flow.js')

//@formatter:off
flow()
    .log('start...')
    .wait(1000)
    .repeat(10)
    /**/.just(() => Math.random() * 100)
    /**/.wait(500)
    /**/.if(v => v > 50)
    /**//**/.log('big {_}')
    /**/.else()
    /**//**/.log('small {_}')
    /**/.end()
    .end()
    .log('repeat done!')
    .wait(1000)
    .just([1, 3, 5, 7, 9, 11])
    .forEach()
    /**/.wait(500)
    /**/.debounce(1000)
    /**/.if(v => v < 5)
    /**//**/.log('{_} < 5')
    /**/.elseif(7)
    /**//**/.log('{_} == 7')
    /**//**/.continue()
    /**/.else()
    /**//**/.log('{_} >= 5')
    /**/.end()
    /**/.log('{_}...')
    .end()
    .log('value {_}')
    .log('forEach done!')
    .while(true)
    /**/.wait(500)
    /**/.map((v) => v + 2)
    /**/.log('{_}')
    /**/.if(v => v > 20)
    /**//**/.log('{_} > 20')
    /**//**/.if(v => v > 40)
    /**//**//**/.break()
    /**//**/.end()
    /**//**/.log('...')
    /**/.end()
    .end()
    .log('while done!')
    .log('end...')
    .match()
    .case()
    .case()
    .default()
    .invoke()
//@formatter:on
